# Default values for bitcoinfn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

function:
  handler: "main.entry"
  sha256Sum: ""

ingress:
  enabled: true
  host: bitcoinfn.cluster.local

resources:
  limits:
    cpu: 400m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 200Mi
