apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: bitcoinfn
  namespace: default
  label:
    created-by: kubeless
    function: bitcoinfn
spec:
  deployment:
    metadata:
      annotations:
        "annotation": "deploy"
    spec:
      replicas: 1
      template:
        metadata:
          annotations:
            "annotation": "pod"
        spec:
          containers:
            - name: "bitcoinfn"
              env:
              - name: CI_ENV
                value: "development"
              resources:
                limits:
                  cpu: 400m
                  memory: 400Mi
                requests:
                  cpu: 200m
                  memory: 200Mi
  runtime: python3.7
  timeout: "300"
  handler: main.entry
  deps: ""
  checksum: sha256:c7c3d204f1d696690927c719772745afad6a249ccceacbd6363f34400fe6fa89
  function: https://github.com/juliocesarscheidt/kubeless-project/raw/main/function.zip?raw=true
  function-content-type: url+zip
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: bitcoinfn
    type: ClusterIP

---

apiVersion: kubeless.io/v1beta1
kind: HTTPTrigger
metadata:
  labels:
    created-by: kubeless
  name: bitcoinfn-http-trigger
  namespace: default
spec:
  basic-auth-secret: ""
  cors-enable: true
  function-name: bitcoinfn
  gateway: nginx
  host-name: bitcoinfn.cluster.local
  path: ""
  tls: false
  tls-secret: ""
